
skillMetadata:
  sections:
    - name: Credentials
      fields:
        - type: label
          label: You can specify the access settings of your vacuum cleaner robot here (comfortable) or locally in the skill directory via credetials.py (secure). If you do not know this info, run getcredentials.py in the skill directory.
        - name: name
          type: text
          label: Name of your robot
          value: ""
        - name: serial
          type: text
          label: Serialnumber of your robot
          value: ""
        - name: secret
          type: password
          label: Secret of your robot
          value: ""
    - name: Rooms
      fields:
        - type: label
          label: You can optionally specify explicit rooms here. You can get available maps via executing getmapids.py in the skill directory.
        - name: rooms
          type: text
          label: Room Configuration
          value: "{'wohnzimmer|wohnen': '2020-05-03T08:10:46Z'}"
