
skillMetadata:
  sections:
    - name: Credentials
      fields:
        - type: label
          label: You can specify the access settings of your vacuum cleaner robot here (comfortable) or locally in the skill directory via credentials.py (secure).
        - name: name
          type: text
          label: Name of your robot
          value: ""
        - name: login 
          type: text
          label: Your Neato login
          value: ""
        - name: passwd 
          type: password
          label: Your Neato password
          value: ""
    - name: Rooms
      fields:
        - type: label
          label: You can optionally specify explicit rooms here. This will override local configuration created automatically via credentials.py.
        - name: rooms
          type: text
          label: Room Configuration
          value: "{'wohnzimmer|wohnen': '2020-05-03T08:10:46Z'}"
